### PR TITLE
HomeWork 5 & 6: Young

### PR DESCRIPTION
**Pull request by w3-9**
轻钱包地址 ： t1o5doelpvfaquee24kehegyckq2h3qr2lkqsgyti
轻钱包转账Hash : bafy2bzacebcu3o4mtnvhqs27fswydtkikevkwlbisamzvfcukju4tdihrrero

默认地址 ： t1xtzcl55f6ct7lrzdrddofun5wpikyto6nj53q5i
存储交易CID ： bafyreifvtgfc5uvnvmt3n34zfo4ppk2fb2o6aegwa4sgivemleup37a7oy

### CODE REVIEW

**Comment by w3-9** [comment]
Also Homework6 for young

NFT : YBAYC is used to test the bayc nft in testnet

contract Address : 0x5377D9388C37C7143E8735c67cCb747e5153eA68
contract creation Hash : 0x5c525b8ab26b1aca2678c8d4b011bcf8c59b9118ada074d3015133f86a76ad60

Owner Address : 0x2e55A4deF72Ab5e2988eCc7750FAdac973C55555

NFT Hash : 0xfae2eda1f5a20665f7643da5bd1f382574cfb5f47649960622fd6b8bdacefd4d

**Comment by w3-9** [comment]
BTW I encountered an error using hardhar to deploy contract

Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}

Is it something to do with the proxy or keep-alive tcp connection?

**Comment by longfeiWan9** [comment]
@Yang94J will you be able to fix the issue with Hardhat ?

**Comment by w3-9** [comment]
> @Yang94J will you be able to fix the issue with Hardhat ?

Not really. This is the proxy issue i guess, so i do the workaround with solidity and metamask.

Also I suggest maybe next time we can use rinkeby or kovan as these netwiorks have free api in infra.

**Pull request merged**
